# Generated by Django 5.0.1 on 2024-03-04 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
