# Generated by Django 5.0.1 on 2024-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_alter_bookmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
